### ISSUE TITLE
ipptool enhancements

### ISSUE THREAD

**Issue by michaelrsweet** [OpenPrinting/cups#153]
Add the following enhancements and bug fixes to `ipptool` (collected from the ippsample project):

- [x] Add directive to monitor "printer-state-reasons" in the background during a test - [ippsample #221](https://github.com/istopwg/ippsample/issues/221)
- [x] Add WITH-DISTINCT-VALUES predicate - [ippsample #209](https://github.com/istopwg/ippsample/issues/209)
- [x] Add -R (repeat) option for server-error-busy - [ippsample #195](https://github.com/istopwg/ippsample/issues/195)
- [x] Support type(LIMIT) syntax, as used in IANA IPP registry - [ippsample #194](https://github.com/istopwg/ippsample/issues/194)
- [x] Fix ipptool using the same random request-id for all requests - [ippsample #188](https://github.com/istopwg/ippsample/issues/188)

**Comment by michaelrsweet** [comment]
Doing development in the "ipptool" branch...

**Comment by michaelrsweet** [comment]
OK, so will only be doing the printer-state-reasons monitoring for this issue...

**Comment by michaelrsweet** [comment]
Dropped several of the less important feature requests for this round of ipptool improvements/bug fixes... We'll do those at a later time...
